algoritmo "Operadores Relacionais"

var

   Txt:Caractere
   Number1, Number2, Number3:Real
   Validator:Logico
   
inicio

      txt <- "digite um numero: "
      Escreva(Txt)
      Leia(Number1)
      Escreva(Txt)
      Leia(Number2)
      Escreva(Txt)
      Leia(Number3)
      
      Verification<- Number1 < (N1 + Number2)
      Escreva( Number1," < ", Number3," + ", Number2," ? ", Verification)

fimalgoritmo